"""empty message

Revision ID: 68fc57b29ba9
Revises: 7268a36a15b9
Create Date: 2024-10-11 19:16:45.548060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fc57b29ba9'
down_revision = '7268a36a15b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_player_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favourite_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favourites_favorite_team_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favourites_favorite_player_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['favourite_player_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['favourite_team_id'], ['id'])
        batch_op.drop_column('favorite_player_id')
        batch_op.drop_column('favorite_team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_player_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favourites_favorite_player_id_fkey', 'players', ['favorite_player_id'], ['id'])
        batch_op.create_foreign_key('favourites_favorite_team_id_fkey', 'teams', ['favorite_team_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('favourite_team_id')
        batch_op.drop_column('favourite_player_id')

    # ### end Alembic commands ###
