"""empty message

Revision ID: 7268a36a15b9
Revises: f8aa5a37ff18
Create Date: 2024-10-11 19:13:49.540129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7268a36a15b9'
down_revision = 'f8aa5a37ff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_player_id', sa.Integer(), nullable=True),
    sa.Column('favorite_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['favorite_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('seasons')
    # ### end Alembic commands ###
