"""empty message

Revision ID: b0da06a18dc3
Revises: 
Create Date: 2024-10-16 19:30:51.199151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0da06a18dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerName', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favourite_player_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favourite_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('games', sa.String(), nullable=True),
    sa.Column('assists', sa.String(), nullable=True),
    sa.Column('points', sa.String(), nullable=True),
    sa.Column('games_started', sa.String(), nullable=True),
    sa.Column('minutes_pg', sa.String(), nullable=True),
    sa.Column('field_goals', sa.String(), nullable=True),
    sa.Column('field_attempts', sa.String(), nullable=True),
    sa.Column('field_percent', sa.String(), nullable=True),
    sa.Column('three_fg', sa.String(), nullable=True),
    sa.Column('three_attempts', sa.String(), nullable=True),
    sa.Column('three_percent', sa.String(), nullable=True),
    sa.Column('two_fg', sa.String(), nullable=True),
    sa.Column('two_attempts', sa.String(), nullable=True),
    sa.Column('two_percent', sa.String(), nullable=True),
    sa.Column('effect_fg_percent', sa.String(), nullable=True),
    sa.Column('ft', sa.String(), nullable=True),
    sa.Column('ft_attempts', sa.String(), nullable=True),
    sa.Column('ft_percent', sa.String(), nullable=True),
    sa.Column('offensive_rb', sa.String(), nullable=True),
    sa.Column('defensive_rb', sa.String(), nullable=True),
    sa.Column('total_rb', sa.String(), nullable=True),
    sa.Column('steals', sa.String(), nullable=True),
    sa.Column('blocks', sa.String(), nullable=True),
    sa.Column('turnovers', sa.String(), nullable=True),
    sa.Column('personal_fouls', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('favorite_players')
    op.drop_table('posts')
    op.drop_table('players')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('seasons')
    # ### end Alembic commands ###
